Add regression test for attrs plugin
This change shows our branch has a regression in the attrs plugin when
re-running dmypy.

The error produced when running this test is:

    Expected:
      foo.py:3: error: Cannot find implementation or library stub for module named "a_module_which_does_not_exist"  [import-not-found]
      foo.py:3: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
      == Return code: 1
    Actual:
      foo.py:3: error: Cannot find implementation or library stub for module named "a_module_which_does_not_exist"  [import-not-found]
      foo.py:3: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
      foo.py:8: error: Unused "type: ignore" comment  [unused-ignore] (diff)
      == Return code: 1